config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :generics
  resources :mains
  resources :schooles
  resources :collegeaands
  resources :mains do
    get "listuser"
    get "listmanager"
  end
  resources :generics do
    resources :users
  end
  resources :mains do
    resources :users
  end
  root to: "mains#index"
  

end

app/models/schoole.rb
class Schoole < ActiveRecord::Base
	belongs_to :user
end

app/controllers/schooles_controller.rb
class SchoolesController < ApplicationController
  before_action :set_schoole, only: [:show, :edit, :update, :destroy]

  # GET /schooles
  # GET /schooles.json
  def index
    @schooles = Schoole.all
  end

  # GET /schooles/1
  # GET /schooles/1.json
  def show
  end

  # GET /schooles/new
  def new
    @schoole = Schoole.new
  end

  # GET /schooles/1/edit
  def edit
  end

  # POST /schooles
  # POST /schooles.json
  def create
    @schoole = Schoole.new(schoole_params)

    respond_to do |format|
      if @schoole.save
        format.html { redirect_to @schoole, notice: 'Schoole was successfully created.' }
        format.json { render :show, status: :created, location: @schoole }
      else
        format.html { render :new }
        format.json { render json: @schoole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schooles/1
  # PATCH/PUT /schooles/1.json
  def update
    respond_to do |format|
      if @schoole.update(schoole_params)
        format.html { redirect_to @schoole, notice: 'Schoole was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoole }
      else
        format.html { render :edit }
        format.json { render json: @schoole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schooles/1
  # DELETE /schooles/1.json
  def destroy
    @schoole.destroy
    respond_to do |format|
      format.html { redirect_to schooles_url, notice: 'Schoole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoole
      @schoole = Schoole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schoole_params
      params.require(:schoole).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :user_id)
    end
end

app/helpers/schooles_helper.rb
module SchoolesHelper
end

app/views/schooles/_form.html.erb
<%= form_for(@schoole) do |f| %>
  <% if @schoole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schoole.errors.count, "error") %> prohibited this schoole from being saved:</h2>

      <ul>
      <% @schoole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :one %><br>
    <%= f.text_field :one %>
  </div>
  <div class="field">
    <%= f.label :two %><br>
    <%= f.text_field :two %>
  </div>
  <div class="field">
    <%= f.label :three %><br>
    <%= f.text_field :three %>
  </div>
  <div class="field">
    <%= f.label :four %><br>
    <%= f.text_field :four %>
  </div>
  <div class="field">
    <%= f.label :five %><br>
    <%= f.text_field :five %>
  </div>
  <div class="field">
    <%= f.label :six %><br>
    <%= f.text_field :six %>
  </div>
  <div class="field">
    <%= f.label :seven %><br>
    <%= f.date_select :seven %>
  </div>
  <div class="field">
    <%= f.label :eight %><br>
    <%= f.date_select :eight %>
  </div>
  <div class="field">
    <%= f.label :nine %><br>
    <%= f.text_area :nine %>
  </div>
  <div class="field">
    <%= f.label :ten %><br>
    <%= f.text_area :ten %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schooles/edit.html.erb
<h1>Editing Schoole</h1>

<%= render 'form' %>

<%= link_to 'Show', @schoole %> |
<%= link_to 'Back', schooles_path %>

app/views/schooles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schooles</h1>

<table>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schooles.each do |schoole| %>
      <tr>
        <td><%= schoole.one %></td>
        <td><%= schoole.two %></td>
        <td><%= schoole.three %></td>
        <td><%= schoole.four %></td>
        <td><%= schoole.five %></td>
        <td><%= schoole.six %></td>
        <td><%= schoole.seven %></td>
        <td><%= schoole.eight %></td>
        <td><%= schoole.nine %></td>
        <td><%= schoole.ten %></td>
        <td><%= link_to 'Show', schoole %></td>
        <td><%= link_to 'Edit', edit_schoole_path(schoole) %></td>
        <td><%= link_to 'Destroy', schoole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schoole', new_schoole_path %>

app/views/schooles/new.html.erb
<h1>New Schoole</h1>

<%= render 'form' %>

<%= link_to 'Back', schooles_path %>

app/views/schooles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @schoole.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @schoole.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @schoole.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @schoole.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @schoole.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @schoole.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @schoole.seven %>
</p>

<p>
  <strong>Eight:</strong>
  <%= @schoole.eight %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @schoole.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @schoole.ten %>
</p>

<%= link_to 'Edit', edit_schoole_path(@schoole) %> |
<%= link_to 'Back', schooles_path %>