config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users
  resources :generics
  resources :mains
  resources :schooles
  resources :collegeaands
  resources :mains do
    get "listuser"
    get "listmanager"
  end
  resources :generics do
    resources :users
  end
  resources :mains do
    resources :users
  end
  root to: "mains#index"
  

end

app/models/collegeaand.rb
class Collegeaand < ActiveRecord::Base
	belongs_to :user
end

app/controllers/collegeaands_controller.rb
class CollegeaandsController < ApplicationController
  before_action :set_collegeaand, only: [:show, :edit, :update, :destroy]

  # GET /collegeaands
  # GET /collegeaands.json
  def index
    @collegeaands = Collegeaand.all
  end

  # GET /collegeaands/1
  # GET /collegeaands/1.json
  def show
  end

  # GET /collegeaands/new
  def new
    @collegeaand = Collegeaand.new
  end

  # GET /collegeaands/1/edit
  def edit
  end

  # POST /collegeaands
  # POST /collegeaands.json
  def create
    @collegeaand = Collegeaand.new(collegeaand_params)

    respond_to do |format|
      if @collegeaand.save
        format.html { redirect_to @collegeaand, notice: 'Collegeaand was successfully created.' }
        format.json { render :show, status: :created, location: @collegeaand }
      else
        format.html { render :new }
        format.json { render json: @collegeaand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collegeaands/1
  # PATCH/PUT /collegeaands/1.json
  def update
    respond_to do |format|
      if @collegeaand.update(collegeaand_params)
        format.html { redirect_to @collegeaand, notice: 'Collegeaand was successfully updated.' }
        format.json { render :show, status: :ok, location: @collegeaand }
      else
        format.html { render :edit }
        format.json { render json: @collegeaand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collegeaands/1
  # DELETE /collegeaands/1.json
  def destroy
    @collegeaand.destroy
    respond_to do |format|
      format.html { redirect_to collegeaands_url, notice: 'Collegeaand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collegeaand
      @collegeaand = Collegeaand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collegeaand_params
      params.require(:collegeaand).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :eleven, :twelve, :user_id)
    end
end

app/helpers/collegeaands_helper.rb
module CollegeaandsHelper
end

app/views/collegeaands/_form.html.erb
<%= form_for(@collegeaand) do |f| %>
  <% if @collegeaand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collegeaand.errors.count, "error") %> prohibited this collegeaand from being saved:</h2>

      <ul>
      <% @collegeaand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :one %><br>
    <%= f.text_field :one %>
  </div>
  <div class="field">
    <%= f.label :two %><br>
    <%= f.text_field :two %>
  </div>
  <div class="field">
    <%= f.label :three %><br>
    <%= f.text_field :three %>
  </div>
  <div class="field">
    <%= f.label :four %><br>
    <%= f.text_field :four %>
  </div>
  <div class="field">
    <%= f.label :five %><br>
    <%= f.text_field :five %>
  </div>
  <div class="field">
    <%= f.label :six %><br>
    <%= f.text_field :six %>
  </div>
  <div class="field">
    <%= f.label :seven %><br>
    <%= f.date_select :seven %>
  </div>
  <div class="field">
    <%= f.label :eight %><br>
    <%= f.date_select :eight %>
  </div>
  <div class="field">
    <%= f.label :nine %><br>
    <%= f.text_area :nine %>
  </div>
  <div class="field">
    <%= f.label :ten %><br>
    <%= f.text_area :ten %>
  </div>
  <div class="field">
    <%= f.label :eleven %><br>
    <%= f.text_area :eleven %>
  </div>
  <div class="field">
    <%= f.label :twelve %><br>
    <%= f.text_area :twelve %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collegeaands/edit.html.erb
<h1>Editing Collegeaand</h1>

<%= render 'form' %>

<%= link_to 'Show', @collegeaand %> |
<%= link_to 'Back', collegeaands_path %>

app/views/collegeaands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collegeaands</h1>
<% if current_user.position == 'Admin' %>

<table>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th>Eleven</th>
      <th>Twelve</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collegeaands.each do |collegeaand| %>
      <tr>
        <td><%= collegeaand.one %></td>
        <td><%= collegeaand.two %></td>
        <td><%= collegeaand.three %></td>
        <td><%= collegeaand.four %></td>
        <td><%= collegeaand.five %></td>
        <td><%= collegeaand.six %></td>
        <td><%= collegeaand.seven %></td>
        <td><%= collegeaand.eight %></td>
        <td><%= collegeaand.nine %></td>
        <td><%= collegeaand.ten %></td>
        <td><%= collegeaand.eleven %></td>
        <td><%= collegeaand.twelve %></td>
        <td><%= link_to 'Show', collegeaand %></td>
        <td><%= link_to 'Edit', edit_collegeaand_path(collegeaand) %></td>
        <td><%= link_to 'Destroy', collegeaand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.position == 'Manager' %>
<table>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th>Eleven</th>
      <th>Twelve</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collegeaands.each do |collegeaand| %>
      <tr>
      <% if current_user.department_name == collegeaand.three %>
        <td><%= collegeaand.one %></td>
        <td><%= collegeaand.two %></td>
        <td><%= collegeaand.three %></td>
        <td><%= collegeaand.four %></td>
        <td><%= collegeaand.five %></td>
        <td><%= collegeaand.six %></td>
        <td><%= collegeaand.seven %></td>
        <td><%= collegeaand.eight %></td>
        <td><%= collegeaand.nine %></td>
        <td><%= collegeaand.ten %></td>
        <td><%= collegeaand.eleven %></td>
        <td><%= collegeaand.twelve %></td>
        <td><%= link_to 'Show', collegeaand %></td>
        <td><%= link_to 'Edit', edit_collegeaand_path(collegeaand) %></td>
        <td><%= link_to 'Destroy', collegeaand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%end%>
<% if current_user.position == 'User' %>
<table>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
      <th>Five</th>
      <th>Six</th>
      <th>Seven</th>
      <th>Eight</th>
      <th>Nine</th>
      <th>Ten</th>
      <th>Eleven</th>
      <th>Twelve</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collegeaands.each do |collegeaand| %>
      <tr>
      <% if current_user.id == collegeaand.user_id %>
        <td><%= collegeaand.one %></td>
        <td><%= collegeaand.two %></td>
        <td><%= collegeaand.three %></td>
        <td><%= collegeaand.four %></td>
        <td><%= collegeaand.five %></td>
        <td><%= collegeaand.six %></td>
        <td><%= collegeaand.seven %></td>
        <td><%= collegeaand.eight %></td>
        <td><%= collegeaand.nine %></td>
        <td><%= collegeaand.ten %></td>
        <td><%= collegeaand.eleven %></td>
        <td><%= collegeaand.twelve %></td>
        <td><%= link_to 'Show', collegeaand %></td>
        <td><%= link_to 'Edit', edit_collegeaand_path(collegeaand) %></td>
        <td><%= link_to 'Destroy', collegeaand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New College of Arts & Sciences Form', new_collegeaand_path %>
<% end %>
<br>
<%= link_to 'Back', mains_path %>

app/views/collegeaands/new.html.erb
<h1>New Collegeaand</h1>

<%= render 'form' %>

<%= link_to 'Back', collegeaands_path %>

app/views/collegeaands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @collegeaand.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @collegeaand.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @collegeaand.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @collegeaand.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @collegeaand.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @collegeaand.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @collegeaand.seven %>
</p>

<p>
  <strong>Eight:</strong>
  <%= @collegeaand.eight %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @collegeaand.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @collegeaand.ten %>
</p>

<p>
  <strong>Eleven:</strong>
  <%= @collegeaand.eleven %>
</p>

<p>
  <strong>Twelve:</strong>
  <%= @collegeaand.twelve %>
</p>

<%= link_to 'Edit', edit_collegeaand_path(@collegeaand) %> |
<%= link_to 'Back', collegeaands_path %>